spring:
  datasource:
    url: jdbc:h2:mem:fretboard;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cloud:
  aws:
    credentials:
      access-key: test-access-key
      secret-key: test-secret-key
    region:
      static: ap-northeast-2
    s3:
      bucket: test-bucket
      image-base-uri: https://test-bucket.s3.amazonaws.com/
      temporary-storage-path: temp/
      image-storage-path: images/

security:
  jwt:
    token:
      secret-key: test-jwt-token-secret-key-for-ci-only
      expire-length: 3600000
    refresh:
      secret-key: test-jwt-refresh-secret-key-for-ci-only
      expire-length: 1209600000