spring:
  application:
    name: FretBoard

  profiles:
    active: dev

#  jpa:
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

