spring:
  application:
    name: FretBoard

  profiles:
    active: prod

#    logging:
#      level:
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

